# _config.yml

name: Justin Andrew Hill
markdown: kramdown
url: "https://HillJ.net"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-scholar

collections:
  posts:
    output: true
    permalink: /hta/:podcast_episode/
    sort_by: episode

podcast:
  title: "Holy Terrain Art"
  subtitle: "Philosophical Sketches of Transpersonal Being-With"
  description: "Holy Terrain Art is a philosophy podcast, sometimes taken for university-level credit and always available for free at HillJ.net/hta/. Teacher exemplary annotations of primary sources are available at HillJ.net/teaching/; you can follow along with these during the lectures. Visual art and lecture notes are available at Instagram.com/HolyTerrainArt/. Episodes are numbered via canons of base-ten for each lecture series; in practice, this numbering system means that, when the podcast starts reading a new primary source, the episode numbers reset at the next base-ten, e.g., 11, 21, 31, 41, etc., each base-ten of which corresponds with the series numbers 1, 2, 3, 4, etc., respectively; base-ten episode numbering allows sub-series to be organized like decimals even though some platforms require episodes be numbered using only integers; sometimes this numbering system results in not all episode numbers being utilized in a base-ten set before starting a new series and before jumping ahead to the next base-ten; e.g., HTA Series 1, on Bergson, is seven episodes, so 18-20 are skipped, holding space to add more later."
  summary: "This podcast is concurrent with curriculi in higher education, adhering to accreditation standards across multiple institutions and systems."
  email: Hill.Justin.Andrew@gmail.com
  language: "en"
  author: Holy Terrain Art
  owner: Justin Andrew Hill
  explicit: false
  category: Education
  subcategory: Higher Education
  tags:
  - university
  - higher education
  - [University Name]
  - students
  - campus life
  - research
  image: /assets/images/podcast-logo.jpeg
  complete: no
  episode: {{ page.episode }}

scholar:
  style: chicago-notes-bibliography-16th-edition
  locale: en
  bibliography: annotations
  sort_by: author, title
  order: ascending
  group_by: author, title
  group_order: ascending
  repository: /assets/pdfs/annotations
  bibliography_template: bibliography
  relative: "/annotations/index.html"
